# Основы R и Rstudio {#sec-whole_r_intro}

В этом разделе книги мы разберемся с основами программирования в R. Мы обучимся всему необходимому для работы в R, в том числе довольно продвинутым инструментам.

-   В главе @sec-intro разбирается установка R и RStudio, как вводить команды и сохранять скрипты, создавать переменные, пользоваться операторами и функциями, разберем типы данных в R.

-   Глава @sec-vector полностью посвящена векторам: их созданию, индексированию и работе с пропущенными значениями (`NA`).

-   В главе @sec-complex_structures разобраны более сложные структуры: список, матрица, массив, датафрейм.

-   В @sec-r_packages мы научимся устанавливать и работать с дополнительными пакетами.

-   Глава @sec-real_data полностью посвящена импорту и экспорту данных, а так же работе с рабочей директорией и проектами RStudio.

-   В главе @sec-loops_conditions мы разберем структуры ветвления (if-else-else if) и их векторизованные аналоги. Кроме того, мы коротко коснемся работы с циклами `for` в R.

-   Глава @sec-functional посвящена созданию пользовательских функций, анонимным функциям и функциям семейства `apply()`.

