project:
  type: book
  output-dir: docs

lang: ru

book:
  title: "Анализ данных и статистика в R"
  author: "Иван Поздняков"
  date: today
  search: 
    location: sidebar
    type: textbox
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    
    - part: 005-whole_r_intro.qmd
      chapters:
      - 010-intro.qmd
      - 013-vector.qmd
      - 016-complex_structures.qmd
      - 020-install.qmd
      - 030-import_data.qmd
      - 040-if_for.qmd
      - 050-functional.qmd
      
    - part: 105-tidyverse.qmd
      chapters:
      - 107-beyond_base_r.qmd
      - 110-tidyverse_basic.qmd
      - 120-tidyverse_advanced.qmd
      
    - part: 205-eda.qmd
      chapters:
      - 210-desc_stats.qmd
      - 220-base_viz.qmd
      - 230-ggplot2.qmd
      - 240-dynamic_viz.qmd
      - 250-rmarkdown.qmd
      
    - part: 305-hyp_test.qmd
      chapters: 
      - 310-infer_stats.qmd
      - 320-ttest.qmd
      - 330-cov_cor.qmd
      - 340-lm.qmd
      - 350-anova.qmd
      - 360-glm.qmd
      - 370-multivariate.qmd
      
    - 410-planning.qmd
    - part: 905-tasks_solutions.qmd
      chapters: 
      - 910-tasks.qmd
      - 920-solutions.qmd
      
    - 950-references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: images/R_stats_pozdniakov_cover.png
  pdf:
    documentclass: book
    mainfont: "Mont"
  epub:
    cover-image: images/R_stats_pozdniakov_cover.png

pdf-engine: lualatex

prefer-html: false

editor: visual

callout-appearance: simple
callout-icon: false

# execute:
#   execute_notebooks: force
#   allow_errors: true
#   cache: true 
  
author:
  - name:
      given: Иван
      family: Поздняков
      literal: И.С. Поздняков
    orcid: 0000-0002-2450-7004
    email: bucherr@yandex.ru

