# О курсе {#sec-about}

Здесь будут материалы для курса "Анализ данных и статистика в R". Эта онлайн-книжка написана с помощью [Quarto](https://quarto.org), [здесь](https://github.com/Pozdniakov/tidy_stats) можно посмотреть код с материалами. Эта книга будет постоянно пополняться, поэтому следите за обновлениями!

Книгу можно использовать как самоучитель, хотя более эффективно ее использовать в качестве дополнительных материалов к соответствующему курсу. Если вы хотите, чтобы я прочитал этот курс в вашей лаборатории или компании, а так же по любым другим вопросам, то пишите мне на почту `ivanspozdniakov@gmail.com`, [VK](https://vk.com/id247411462) или в *Telegra*m:`@pozdniakovivan` (лучше писать в *Telegram).*

Эта книжка абсолютно бесплатна, ее можно скачивать, делиться ей с другими, я буду только рад этому!

Если вы хотите поддержать мою работу, то можете оформить подписку:

-   на [Патреоне](https://patreon.com/pozdniakov_rstats) (если вы находитесь за границей России)
-   на [Бусти](https://boosty.to/pozdniakov_rstats) (если вы находитесь в России)
